/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class common_net_keepalive_LTSocketImpl_ReadCallback */

#ifndef _Included_common_net_keepalive_LTSocketImpl_ReadCallback
#define _Included_common_net_keepalive_LTSocketImpl_ReadCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
