/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class common_net_keepalive_LTSocketImpl */

#ifndef _Included_common_net_keepalive_LTSocketImpl
#define _Included_common_net_keepalive_LTSocketImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     common_net_keepalive_LTSocketImpl
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_common_net_keepalive_LTSocketImpl_init
  (JNIEnv *, jobject);

/*
 * Class:     common_net_keepalive_LTSocketImpl
 * Method:    connect
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_common_net_keepalive_LTSocketImpl_connect
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     common_net_keepalive_LTSocketImpl
 * Method:    send
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_common_net_keepalive_LTSocketImpl_send
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     common_net_keepalive_LTSocketImpl
 * Method:    readBlock
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_common_net_keepalive_LTSocketImpl_readBlock
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     common_net_keepalive_LTSocketImpl
 * Method:    delete
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_common_net_keepalive_LTSocketImpl_delete
  (JNIEnv *, jobject);

/*
 * Class:     common_net_keepalive_LTSocketImpl
 * Method:    setKeepalive
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_common_net_keepalive_LTSocketImpl_setKeepalive
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
